version: "3"
services:
  postgres-db:
    image: postgres:12
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    # networks:
    #   - container_networks
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: "no"
    ports:
      - 9002:80
    environment:
      - "PGADMIN_DEFAULT_EMAIL=andifaizal@refactory.id"
      - "PGADMIN_DEFAULT_PASSWORD=password"
    depends_on:
      - postgres-db
    # networks:
    #   - container_networks
    # volumes:
    #   - pgadmin-data:/var/lib/pgadmin
